//! Server-side rendered HTML for `GET /r/{id}`: no JS, inline CSS. Renders
//! directly from the stored `serde_json::Value` (the same shape as the
//! `--share`/`--json` payload) rather than deserializing into `Report` /
//! `RenderedVerdict`, so the server keeps working even if the client schema
//! grows fields it doesn't know about yet.
//!
//! Every user-controlled string (hostnames, evidence text, error messages,
//! …) is HTML-escaped before being written into the page.

use crate::i18n::Lang;
use serde_json::Value;

/// Escapes the five HTML-significant characters. Used for every piece of
/// text that ultimately comes from user input (the diagnosis target, error
/// strings, evidence bullets, …) before it is embedded in the page.
pub fn escape_html(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

fn lang_from_value(v: &Value) -> Lang {
    match v.get("created_lang").and_then(Value::as_str) {
        Some("en") => Lang::En,
        _ => Lang::Ja, // default, per spec
    }
}

fn s(v: &Value, key: &str) -> String {
    v.get(key)
        .and_then(Value::as_str)
        .map(escape_html)
        .unwrap_or_default()
}

fn opt_str(v: &Value, key: &str) -> Option<String> {
    v.get(key).and_then(Value::as_str).map(escape_html)
}

fn label(lang: Lang, en: &str, ja: &str) -> &'static str {
    // Small local i18n helper: leaks a short 'static str via Box::leak is
    // overkill here, so callers pass through pre-baked &'static str pairs
    // instead (see call sites below) — this fn exists only for symmetry
    // with crate::i18n's `match lang { ... }` style.
    match lang {
        Lang::En => Box::leak(en.to_string().into_boxed_str()),
        Lang::Ja => Box::leak(ja.to_string().into_boxed_str()),
    }
}

/// Culprit severity used to color the verdict block. `NoProblem` is green,
/// everything else is red — matching the CLI's own color coding
/// (`print_verdict_block` in `main.rs`).
fn verdict_is_ok(v: &Value) -> bool {
    v.pointer("/verdict/culprit_code")
        .and_then(Value::as_str)
        .map(|c| c == "no_problem")
        .unwrap_or(false)
}

/// Renders a full standalone HTML page for a stored report `Value`.
/// `id` and `netblame_version` are used in the footer/title; both are
/// escaped even though in practice `id` is validated upstream to be
/// alphanumeric.
pub fn render_report_page(id: &str, report: &Value) -> String {
    let lang = lang_from_value(report);
    let ok = verdict_is_ok(report);
    let host = report
        .pointer("/report/target/host")
        .and_then(Value::as_str)
        .map(escape_html)
        .unwrap_or_else(|| "?".to_string());
    let version = opt_str(report, "netblame_version").unwrap_or_else(|| "?".to_string());

    let title = label(lang, "netblame report", "netblame レポート");
    let verdict_label = label(lang, "Verdict", "判定");
    let evidence_label = label(lang, "Evidence", "根拠");
    let notes_label = label(lang, "Notes", "所見");
    let next_step_label = label(lang, "Next step", "次の一手");
    let target_label = label(lang, "Target", "対象");
    let generated_by = label(lang, "generated by netblame", "netblame により生成");

    let headline = report
        .pointer("/verdict/headline")
        .and_then(Value::as_str)
        .map(escape_html)
        .unwrap_or_default();
    let next_step = report
        .pointer("/verdict/next_step")
        .and_then(Value::as_str)
        .map(escape_html)
        .unwrap_or_default();

    let evidence_items = render_string_list(report.pointer("/verdict/evidence"));
    let secondary_items = render_string_list(report.pointer("/verdict/secondary"));

    let verdict_class = if ok { "verdict-ok" } else { "verdict-bad" };

    let dns_table = render_dns_table(report.pointer("/report/dns/sources"), lang);
    let tcp_table = render_tcp_table(report.pointer("/report/tcp/probes"), lang);
    let tls_block = render_tls_block(report.pointer("/report/tls"), lang);
    let http_block = render_http_block(report.pointer("/report/http"), lang);
    let quic_block = render_quic_block(report.pointer("/report/quic"), lang);
    let path_block = render_path_block(report.pointer("/report/path"), lang);
    let trace_block = render_trace_block(report.pointer("/report/trace"), lang);

    let notes_section = if secondary_items.is_empty() {
        String::new()
    } else {
        format!(
            "<h2>{notes_label}</h2><ul class=\"notes\">{secondary_items}</ul>",
            notes_label = notes_label,
            secondary_items = secondary_items
        )
    };

    format!(
        r#"<!doctype html>
<html lang="{html_lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — {host}</title>
<style>
{css}
</style>
</head>
<body>
<main>
<h1>{title}: {host}</h1>
<section class="verdict {verdict_class}">
<h2>{verdict_label}</h2>
<p class="headline">{headline}</p>
<h3>{evidence_label}</h3>
<ul>{evidence_items}</ul>
{notes_section}
<h3>{next_step_label}</h3>
<p>{next_step}</p>
</section>
<section>
<h2>{target_label}</h2>
{dns_table}
{tcp_table}
{tls_block}
{http_block}
{quic_block}
{path_block}
{trace_block}
</section>
<footer>{generated_by} v{version} — id {id_escaped}</footer>
</main>
</body>
</html>
"#,
        html_lang = if lang == Lang::Ja { "ja" } else { "en" },
        title = title,
        host = host,
        css = CSS,
        verdict_class = verdict_class,
        verdict_label = verdict_label,
        headline = headline,
        evidence_label = evidence_label,
        evidence_items = evidence_items,
        notes_section = notes_section,
        next_step_label = next_step_label,
        next_step = next_step,
        target_label = target_label,
        dns_table = dns_table,
        tcp_table = tcp_table,
        tls_block = tls_block,
        http_block = http_block,
        quic_block = quic_block,
        path_block = path_block,
        trace_block = trace_block,
        generated_by = generated_by,
        version = escape_html(&version),
        id_escaped = escape_html(id),
    )
}

fn render_string_list(v: Option<&Value>) -> String {
    let Some(Value::Array(items)) = v else {
        return String::new();
    };
    items
        .iter()
        .filter_map(Value::as_str)
        .map(|s| format!("<li>{}</li>", escape_html(s)))
        .collect::<Vec<_>>()
        .join("")
}

fn outcome_code(v: &Value) -> String {
    v.get("outcome")
        .and_then(|o| o.get("code"))
        .and_then(Value::as_str)
        .map(escape_html)
        .unwrap_or_else(|| "?".to_string())
}

fn render_dns_table(v: Option<&Value>, lang: Lang) -> String {
    let Some(Value::Array(sources)) = v else {
        return String::new();
    };
    if sources.is_empty() {
        return String::new();
    }
    let heading = label(lang, "DNS", "DNS");
    let th_source = label(lang, "Source", "問い合わせ先");
    let th_outcome = label(lang, "Outcome", "結果");
    let th_latency = label(lang, "Latency", "応答時間");
    let th_answers = label(lang, "Answers", "回答");

    let rows = sources
        .iter()
        .map(|src| {
            let src_label = s(src, "label");
            let outcome = outcome_code(src);
            let latency = src
                .get("latency_ms")
                .and_then(Value::as_f64)
                .map(|ms| format!("{ms:.0}ms"))
                .unwrap_or_else(|| "-".to_string());
            let ips = src
                .get("ips")
                .and_then(Value::as_array)
                .map(|arr| {
                    arr.iter()
                        .filter_map(Value::as_str)
                        .map(escape_html)
                        .collect::<Vec<_>>()
                        .join(", ")
                })
                .unwrap_or_default();
            format!(
                "<tr><td>{src_label}</td><td>{outcome}</td><td>{latency}</td><td>{ips}</td></tr>"
            )
        })
        .collect::<String>();

    format!(
        "<h3>{heading}</h3><table><thead><tr><th>{th_source}</th><th>{th_outcome}</th><th>{th_latency}</th><th>{th_answers}</th></tr></thead><tbody>{rows}</tbody></table>"
    )
}

fn render_tcp_table(v: Option<&Value>, lang: Lang) -> String {
    let Some(Value::Array(probes)) = v else {
        return String::new();
    };
    if probes.is_empty() {
        return String::new();
    }
    let heading = label(lang, "TCP", "TCP");
    let th_ip = label(lang, "IP", "IP");
    let th_outcome = label(lang, "Outcome", "結果");
    let th_success = label(lang, "Success", "成功");
    let th_rtt = label(lang, "min/avg/max", "min/avg/max");

    let rows = probes
        .iter()
        .map(|p| {
            let ip = s(p, "ip");
            let port = p.get("port").and_then(Value::as_u64).unwrap_or(0);
            let outcome = outcome_code(p);
            let successes = p.get("successes").and_then(Value::as_u64).unwrap_or(0);
            let samples = p.get("samples").and_then(Value::as_u64).unwrap_or(0);
            let fmt_ms = |key: &str| {
                p.get(key)
                    .and_then(Value::as_f64)
                    .map(|ms| format!("{ms:.0}ms"))
                    .unwrap_or_else(|| "-".to_string())
            };
            format!(
                "<tr><td>{ip}:{port}</td><td>{outcome}</td><td>{successes}/{samples}</td><td>{min}/{avg}/{max}</td></tr>",
                min = fmt_ms("min_ms"),
                avg = fmt_ms("avg_ms"),
                max = fmt_ms("max_ms"),
            )
        })
        .collect::<String>();

    format!(
        "<h3>{heading}</h3><table><thead><tr><th>{th_ip}</th><th>{th_outcome}</th><th>{th_success}</th><th>{th_rtt}</th></tr></thead><tbody>{rows}</tbody></table>"
    )
}

fn render_tls_block(v: Option<&Value>, lang: Lang) -> String {
    let Some(v) = v.filter(|v| !v.is_null()) else {
        return String::new();
    };
    let heading = label(lang, "TLS", "TLS");
    let verified = v.get("verified").and_then(Value::as_bool).unwrap_or(false);
    let version = opt_str(v, "version").unwrap_or_else(|| "?".to_string());
    let days = v.get("days_until_expiry").and_then(Value::as_i64);
    let error = opt_str(v, "error");
    let verified_label = label(lang, "verified", "検証");
    let expiry_label = label(lang, "expires in", "残り有効期間");
    let days_unit = label(lang, "days", "日");

    let mut body = format!(
        "<p>{verified_label}: {verified}, {version}</p>",
        verified = if verified { "OK" } else { "FAIL" },
    );
    if let Some(d) = days {
        body.push_str(&format!("<p>{expiry_label}: {d} {days_unit}</p>"));
    }
    if let Some(e) = error {
        body.push_str(&format!("<p class=\"err\">{e}</p>"));
    }
    format!("<h3>{heading}</h3>{body}")
}

fn render_http_block(v: Option<&Value>, lang: Lang) -> String {
    let Some(v) = v.filter(|v| !v.is_null()) else {
        return String::new();
    };
    let heading = label(lang, "HTTP", "HTTP");
    let status = v
        .get("status")
        .and_then(Value::as_u64)
        .map(|s| s.to_string())
        .unwrap_or_else(|| "-".to_string());
    let ttfb = v
        .get("ttfb_ms")
        .and_then(Value::as_f64)
        .map(|ms| format!("{ms:.0}ms"))
        .unwrap_or_else(|| "-".to_string());
    let total = v
        .get("total_ms")
        .and_then(Value::as_f64)
        .map(|ms| format!("{ms:.0}ms"))
        .unwrap_or_else(|| "-".to_string());
    let error = opt_str(v, "error");
    let status_label = label(lang, "status", "ステータス");
    let ttfb_label = label(lang, "TTFB", "TTFB");
    let total_label = label(lang, "total", "合計");

    let mut body =
        format!("<p>{status_label}: {status} — {ttfb_label} {ttfb} / {total_label} {total}</p>");
    if let Some(e) = error {
        body.push_str(&format!("<p class=\"err\">{e}</p>"));
    }
    format!("<h3>{heading}</h3>{body}")
}

fn render_quic_block(v: Option<&Value>, lang: Lang) -> String {
    let Some(v) = v.filter(|v| !v.is_null()) else {
        return String::new();
    };
    let heading = label(lang, "QUIC/HTTP3", "QUIC/HTTP3");
    let code = outcome_code(v);
    format!("<h3>{heading}</h3><p>{code}</p>")
}

fn render_path_block(v: Option<&Value>, lang: Lang) -> String {
    let Some(v) = v.filter(|v| !v.is_null()) else {
        return String::new();
    };
    let heading = label(lang, "Path quality", "経路品質");
    let loss = v.get("loss_pct").and_then(Value::as_f64).unwrap_or(0.0);
    let jitter = v
        .get("jitter_ms")
        .and_then(Value::as_f64)
        .map(|ms| format!("{ms:.0}ms"))
        .unwrap_or_else(|| "-".to_string());
    let loss_label = label(lang, "loss", "ロス");
    let jitter_label = label(lang, "jitter", "ジッタ");
    format!("<h3>{heading}</h3><p>{loss_label} {loss:.0}% / {jitter_label} {jitter}</p>")
}

fn render_trace_block(v: Option<&Value>, lang: Lang) -> String {
    let Some(v) = v.filter(|v| !v.is_null()) else {
        return String::new();
    };
    let heading = label(lang, "Path trace", "経路トレース");
    let hops = v.pointer("/data/hops").and_then(Value::as_array);
    let Some(hops) = hops else {
        return String::new();
    };
    let no_reply = label(lang, "no reply", "応答なし");
    let rows = hops
        .iter()
        .map(|h| {
            let index = h.get("index").and_then(Value::as_u64).unwrap_or(0);
            let addr = h
                .get("addr")
                .and_then(Value::as_str)
                .map(escape_html)
                .unwrap_or_else(|| format!("* ({no_reply})"));
            let rtt = h
                .get("rtt_ms")
                .and_then(Value::as_f64)
                .map(|ms| format!("{ms:.0}ms"))
                .unwrap_or_else(|| "-".to_string());
            format!("<tr><td>{index}</td><td>{addr}</td><td>{rtt}</td></tr>")
        })
        .collect::<String>();
    if rows.is_empty() {
        return String::new();
    }
    format!("<h3>{heading}</h3><table><tbody>{rows}</tbody></table>")
}

/// Renders the 404 page for an unknown report id.
pub fn render_not_found_page(lang: Lang) -> String {
    let title = label(lang, "Report not found", "レポートが見つかりません");
    let body = label(
        lang,
        "This report does not exist, or has expired and been removed.",
        "このレポートは存在しないか、期限切れで削除されています。",
    );
    format!(
        r#"<!doctype html>
<html lang="{html_lang}">
<head><meta charset="utf-8"><title>{title}</title><style>{css}</style></head>
<body><main><h1>404 — {title}</h1><p>{body}</p></main></body>
</html>
"#,
        html_lang = if lang == Lang::Ja { "ja" } else { "en" },
        title = title,
        css = CSS,
        body = body,
    )
}

const CSS: &str = r#"
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #0f1115; color: #e6e6e6; margin: 0; padding: 2rem 1rem; }
main { max-width: 760px; margin: 0 auto; }
h1 { font-size: 1.4rem; word-break: break-all; }
section { background: #171a21; border-radius: 8px; padding: 1rem 1.25rem; margin-bottom: 1rem; }
.verdict.verdict-ok { border-left: 4px solid #2ecc71; }
.verdict.verdict-bad { border-left: 4px solid #e74c3c; }
.headline { font-size: 1.1rem; font-weight: 600; }
table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; font-size: 0.9rem; }
th, td { text-align: left; padding: 0.25rem 0.5rem; border-bottom: 1px solid #2a2f3a; }
.err { color: #e74c3c; }
footer { text-align: center; color: #666; font-size: 0.8rem; margin-top: 2rem; }
ul { padding-left: 1.25rem; }
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn fixture() -> Value {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/tests/fixtures/sample_report.json"
        );
        let raw = fs::read_to_string(path).expect("fixture file should exist");
        serde_json::from_str(&raw).expect("fixture should be valid JSON")
    }

    #[test]
    fn escapes_all_five_special_characters() {
        let escaped = escape_html(r#"<script>alert('x')</script> & "quotes""#);
        assert!(!escaped.contains('<'));
        assert!(!escaped.contains('>'));
        assert!(escaped.contains("&lt;script&gt;"));
        assert!(escaped.contains("&amp;"));
        assert!(escaped.contains("&quot;"));
        assert!(escaped.contains("&#39;"));
    }

    #[test]
    fn renders_host_and_verdict_headline() {
        let report = fixture();
        let html = render_report_page("ab12cd34ef", &report);
        assert!(html.contains("example.com"));
        assert!(html.contains("No problem found") || html.contains("問題は見つかりませんでした"));
    }

    #[test]
    fn xss_payload_in_evidence_is_escaped_not_executed() {
        let report = fixture();
        let html = render_report_page("ab12cd34ef", &report);
        assert!(
            !html.contains("<script>alert(1)</script>"),
            "raw script tag must never appear unescaped in output"
        );
        assert!(html.contains("&lt;script&gt;alert(1)&lt;/script&gt;"));
        assert!(html.contains("&quot;quoted&quot;"));
    }

    #[test]
    fn verdict_ok_gets_ok_css_class() {
        let report = fixture();
        let html = render_report_page("ab12cd34ef", &report);
        assert!(html.contains(r#"class="verdict verdict-ok""#));
        assert!(!html.contains(r#"class="verdict verdict-bad""#));
    }

    #[test]
    fn renders_dns_and_tcp_tables() {
        let report = fixture();
        let html = render_report_page("ab12cd34ef", &report);
        assert!(html.contains("104.20.23.154"));
        assert!(html.contains("system resolver") || html.contains("システムリゾルバ"));
    }

    #[test]
    fn footer_contains_version_and_id() {
        let report = fixture();
        let html = render_report_page("myid123456", &report);
        assert!(html.contains("0.5.0"));
        assert!(html.contains("myid123456"));
        assert!(html.contains("generated by netblame") || html.contains("netblame により生成"));
    }

    #[test]
    fn defaults_to_japanese_when_lang_missing() {
        let mut report = fixture();
        report.as_object_mut().unwrap().remove("created_lang");
        assert_eq!(lang_from_value(&report), Lang::Ja);
    }

    #[test]
    fn not_found_page_renders_in_requested_language() {
        let en = render_not_found_page(Lang::En);
        let ja = render_not_found_page(Lang::Ja);
        assert!(en.contains("Report not found"));
        assert!(ja.contains("見つかりません"));
    }

    #[test]
    fn malformed_report_does_not_panic() {
        let empty = serde_json::json!({});
        let html = render_report_page("ab12cd34ef", &empty);
        assert!(html.contains("<html"));
    }
}
